#ifndef OPCODE_H
#define OPCODE_H

enum Opcode
{
    FIRST_OPCODE                = 0,
    CMSG_HANDSHAKE_REQUEST      = FIRST_OPCODE,
    SMSG_HANDSHAKE_RESPONSE,
    CMSG_GAME_LIST_REQUEST,
    SMSG_GAME_LIST_RESPONSE,
    CMSG_GAME_JOIN_REQUEST,
    SMSG_GAME_JOIN_RESPONSE,
    CMSG_MAP_LIST_REQUEST,
    SMSG_MAP_LIST_RESPONSE,
    CMSG_GAME_CREATE_REQUEST,
    SMSG_GAME_CREATE_RESPONSE,
    MAX_OPCODES
};

#endif // OPCODE_H
